/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package net.lapthorn.plugins

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'net.lapthorn.plugins.modules-check' plugin.
 */
class ModulesCheckPluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("net.lapthorn.plugins.modules-check")

        // Verify the result
        assertNotNull(project.tasks.findByName("modules-check"))
    }
}
