/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package net.lapthorn.plugins

import org.gradle.api.GradleException
import java.io.File
import org.gradle.testkit.runner.GradleRunner
import kotlin.test.Test
import kotlin.test.assertTrue

/**
 * A simple functional test for the 'net.lapthorn.plugins.modules-check' plugin.
 */
class ModulesCheckPluginFunctionalTest {
//    @Test(expected = GradleException::class)
//    fun `can run task`() {
//        // Setup the test build
//        val projectDir = File("build/functionalTest")
//        projectDir.mkdirs()
//        projectDir.resolve("settings.gradle").writeText("")
//        projectDir.resolve("build.gradle").writeText("""
//            plugins {
//                id('net.lapthorn.plugins.modules-check')
//            }
//        """)
//
//        // Run the build
//        val runner = GradleRunner.create()
//        runner.forwardOutput()
//        runner.withPluginClasspath()
//        runner.withArguments("modules-check")
//        runner.withProjectDir(projectDir)
//        val result = runner.build();
//
//        // Verify the result
//        assertTrue(result.output.contains("Hello from plugin 'net.lapthorn.plugins.modules-check'"))
//    }
}
